apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-simple-webserver
  labels:
    app: go-simple-webserver
spec:
  replicas: 10
  selector:
    matchLabels:
      app: go-simple-webserver
  template:
    metadata:
      labels:
        app: go-simple-webserver
    spec:
      containers:
        - name: webserver
          image: ghcr.io/gabriel-mazilu/ci_cd_lab@sha256:48ed7b5f082586439c0e97764939bc1f474045ca8e690d2409b5b36ab2be1959
          ports:
            - containerPort: 8080
